packages:
  - "."

minimumReleaseAge: 1400 # 1 day
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  lefthook: true
