name: Deploy Worker
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "worker/**"
      - "shared/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/deploy-worker.yaml"

jobs:
  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build worker
        run: pnpm build:worker

      - name: Deploy worker
        id: wrangler-deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: worker
